--- # три тире сигнализируют начало нового yml-файла
name: unit-tests-github-actions
on: [push] # на событие push в репозитории запускается рабочий процесс (jobs) ниже

jobs:
  test-lint: # название рабочего процесса
    name: Test and Lint  # название, которое будет видно из интерфейса GitHub Actions
    runs-on: ubuntu-20.04
    steps: # шаги исполняются поэтапно сверху вниз
      - name: Login to Docker Hub # название для этого конкретного шага
        uses: docker/login-action@v2  # pre-made action из GitHub Actions Marketplace, чтобы не писать свой алгоритм логинки в DockerHub https://github.com/marketplace/actions/docker-login
        with:
          username: ${{ secrets.DOCKERHUB_USER }}  # эти переменные должны совпадать с теми, которые мы добавили в настройки репозитория в Secrets -> Actions
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3 # pre-made action от самого GitHub, который проверяет код в репозитории на доступность для виртуального окружения GitHub Actions
      - name: Test
        run: docker-compose -f ${{ github.workspace }}/backend/docker-compose-dev.yml run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
  #    - name: Lint
  #      run: docker-compose -f ${{ github.workspace }}/backend/docker-compose-dev.yml run --rm app sh -c "flake8"